'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('phones', [
    {
      model: 'Note 11',
      brand: 'Redmi',
      year_of_manufacture: '2022-07-01',
      ram_size: 4,
      screen_diagonal: 5.5,
      is_nfc: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      model: 'X',
      brand: 'IPhone',
      year_of_manufacture: '2018-09-01',
      ram_size: 4,
      screen_diagonal: 4.5,
      is_nfc: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      model: '11',
      brand: 'IPhone',
      year_of_manufacture: '2019-10-01',
      ram_size: 8,
      screen_diagonal: 5,
      is_nfc: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      model: 'Note 12',
      brand: 'Redmi',
      year_of_manufacture: '2023-06-01',
      ram_size: 8,
      screen_diagonal: 6,
      is_nfc: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      model: 'Ultra 24',
      brand: 'Samsung',
      year_of_manufacture: '2024-05-01',
      ram_size: 16,
      screen_diagonal: 6,
      is_nfc: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      model: 'A7',
      brand: 'Redmi',
      year_of_manufacture: '2019-07-01',
      ram_size: 2,
      screen_diagonal: 4.5,
      is_nfc: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      model: 'Note 10',
      brand: 'Redmi',
      year_of_manufacture: '2021-07-01',
      ram_size: 3,
      screen_diagonal: 5,
      is_nfc: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      model: 'SE',
      brand: 'IPhone',
      year_of_manufacture: '2016-07-01',
      ram_size: 3,
      screen_diagonal: 4,
      is_nfc: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      model: '6',
      brand: 'IPhone',
      year_of_manufacture: '2010-07-01',
      ram_size: 2,
      screen_diagonal: 4,
      is_nfc: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      model: 'J19',
      brand: 'Samsung',
      year_of_manufacture: '2019-07-01',
      ram_size: 2,
      screen_diagonal: 4,
      is_nfc: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      model: '10',
      brand: 'Redmi',
      year_of_manufacture: '2021-07-01',
      ram_size: 4,
      screen_diagonal: 5.5,
      is_nfc: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      model: 'Note 13',
      brand: 'Redmi',
      year_of_manufacture: '2023-07-01',
      ram_size: 6,
      screen_diagonal: 6,
      is_nfc: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ], {});
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('phones', null, {});
  }
};
